### ISSUE TITLE
Recomputer R100x,  RTC PCF8563 doesn't get recognized on OpenWRT

### ISSUE THREAD

**Issue by massiekris** [Seeed-Studio/seeed-linux-dtoverlays#109]
**Describe the bug**
Setting up OpenWRT  (kernel 5.15.134) on the R100x using the reComputer-R100x-overlay.dts file, fails to load the RTC driver.

After some trial and error, if I change line  134, from 
pcf8563w@51 to pcf8563@51 everything works.

Is there a reason for the additional 'w'?

**Comment by bigbearishappy** [comment]
It seems that the dts node of rtc is copied from Reterminal DM(plus). We did this because we modify the driver of pcf8563 and renamed it to pcf8563w.[Here](https://github.com/Seeed-Studio/seeed-linux-dtoverlays/blob/master/modules/rtc-pcf8563w/rtc-pcf8563w.c) is the driver souce code of it. 

Since you can make it work by changing the name of rtc node. I think you can create a PR to our repo for better compatibility.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
