### ISSUE TITLE
USB device is not shown as /dev/tty* after seeed-linux-dtoverlays installation on reTerminalDM

### ISSUE THREAD

**Issue by symstopje** [Seeed-Studio/seeed-linux-dtoverlays#66]
**Describe the bug**
some usb devices can be seen in lsusb but link in /dev/ folder is not populated

**To Reproduce**
1. On fresh raspbianOS 64 Lite, before installing seeed-linux-dtoverlays  connect e.g. XIAO nRF53840-sense to USB - new /dev/ttyACM2 is shown
2. install seeed-linux-dtoverlays   (sudo ./scripts/reTerminal.sh --device reTerminal-plus)
3. after restart connect same board again  - nothing new is shown in /dev

Checked on few different serial USB devices

**Expected behavior**
new device e.g. /dev/ttyUSB0 should be available

**Desktop (please complete the following information):**
 - OS: Linux 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

**Comment by bigbearishappy** [comment]
Because we blacklist the original cdc_acm driver while we install the seeed-linux-dtoverlays. We do this because the usb-to-ttl chip(ch342f) output some gibberish at system startup. So we use the kernel driver from ch342f and disable the cdc_acm.
To fix this. You remove the `blacklist cdc_acm` in /etc/modprobe.d/raspi-blacklist.conf and reboot the system.
